from __future__ import annotations

import json

from src.semantic_registry.pipeline.candidate_generator import CandidateGenerator
from src.semantic_registry.pipeline.llm_gateway_types import LLMResponse
from src.semantic_registry.pipeline.state_machine import PipelineContext
from src.semantic_registry.resolver.plan import SemanticQueryPlan


class FakeGateway:
    def __init__(self) -> None:
        self.prompts: list[str] = []

    def generate(self, prompt: str) -> LLMResponse:
        self.prompts.append(prompt)
        return LLMResponse(
            sql="SELECT SUM(paid_gmv_amt) AS paid_gmv FROM orders",
            assumptions=[],
            tables_used=["orders"],
            columns_used=["paid_gmv_amt"],
            confidence="high",
            reasoning_summary="Generated by fake gateway.",
        )


def test_generate_candidates_returns_two_valid_strategies() -> None:
    context = PipelineContext(
        question="show paid GMV by channel",
        semantic_plan=SemanticQueryPlan(
            metric="paid_gmv",
            dimension="channel",
            time_semantics="payment_date",
            domain="commerce",
        ),
        context_prompt="""
<generation_context>
{
  "semantic_plan": {
    "metric": "paid_gmv",
    "dimension": "channel",
    "time_range": null,
    "time_semantics": "payment_date",
    "domain": "commerce",
    "filters": []
  },
  "physical_mapping": {
    "table": "orders",
    "metric_column": "paid_gmv_amt",
    "metric_expression": "paid_gmv_amt",
    "dimension_column": "channel",
    "time_column": "payment_dt",
    "aggregation": "sum"
  },
  "candidate_tables": ["orders"],
  "known_caveats": []
}
</generation_context>
""",
    )

    candidates = CandidateGenerator().generate_candidates(context)

    assert len(candidates) == 2
    assert candidates[0].generation_strategy == "direct"
    assert candidates[1].generation_strategy == "plan_first"
    assert all(candidate.parse_success for candidate in candidates)
    assert all(candidate.sql.startswith("SELECT") for candidate in candidates)


def test_generate_candidates_records_llm_trace_responses() -> None:
    context = PipelineContext(
        question="show paid GMV",
        context_prompt="prompt a",
    )
    gateway = FakeGateway()
    generator = CandidateGenerator(llm_gateway=gateway)
    context.record_llm_trace("candidate_a", prompt=context.context_prompt)
    context.record_llm_trace("candidate_b", prompt=generator._plan_first_prompt(context.context_prompt or ""))

    candidates = generator.generate_candidates(context)

    assert len(candidates) == 2
    assert context.llm_trace["candidate_a"]["prompt"] == "prompt a"
    assert context.llm_trace["candidate_a"]["response"] is not None
    assert json.loads(context.llm_trace["candidate_a"]["response"])["sql"].startswith("SELECT")
    assert context.llm_trace["candidate_b"]["prompt"] == gateway.prompts[1]
    assert json.loads(context.llm_trace["candidate_b"]["response"])["confidence"] == "high"
